--1.
CREATE TABLE TB_CATEGORY(
        TB_NAME VARCHAR2(10),
        TB_USE_YN CHAR(1)DEFAULT'Y'
        );

--2.
CREATE TABLE TB_CLASS_TYPE(
        TB_NO VARCHAR2(5)PRIMARY KEY,
        TB_NAME VARCHAR2(10)
        );
        
--3.
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(TB_NAME);

--4.
ALTER TABLE TB_CLASS_TYPE MODIFY TB_NAME NOT NULL;

--5. 크기만 변경하시오 (수정 : MODIFY)
ALTER TABLE TB_CLASS_TYPE MODIFY TB_NO VARCHAR2(10)
                          MODIFY TB_NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY MODIFY TB_NAME VARCHAR2(20);                     

--6.
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7.???
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007535 TO PK_CALSS_TYPE_NO;

--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

--9.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN

--10.
CREATE OR REPLACE VIEW VW_학생일반정보(학번,학생이름,주소)
AS SELECT STUDENT_NO,STUDENT_NAME,STUDENT_ADDRESS
    FROM TB_STUDENT;
    
--11.

--15.
SELECT *
FROM(
        SELECT CLASS_NO 과목번호, CLASS_NAME과목이름,COUNT(*)"누적수가앵수(명)"
        FROM TB_GRADE
        JOIN TB_CLASS USING(CLASS_NO)
        WHERE TERM_NO LIKE '2009%'
           OR TERM_NO LIKE '2008%'
           OR TERM_NO LIKE '2007%'
           OR TERM_NO LIKE '2006%'
           OR TERM_NO LIKE '2005%'
        GROUP BY CLASS_NO
        ORDER BY 2 DESC
        )
WHERE ROWNNUM <= 3;